name: CI Build & Lint

on:
  push:
    branches: [main]

jobs:
  lint-and-test-python:
    name: Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install boto3 openai

      - name: Run Python syntax check
        run: |
          python -m py_compile minecraft-project/mc_data/LLM/chatMessagesLLM.py
          python -m py_compile minecraft-project/mc_data/LLM/load_saveChat.py

  docker-build:
    name: Test Docker Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minecraft-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t minecraft-llm .
      
      - name: Docker-compose up
        run: docker compose up -d

      - name: Docker-compose down
        run: docker compose down

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: minecraft-project/Dockerfile
          

  terraform-validate:
    name: Validate Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: minecraft-project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

  java-plugins:
    name: Build with Maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: chatPlugin
        run: mvn clean package
